HOST: http://youyanchu.gaiamagic.com/api

--- API youyanchu.gaiamagic.com ---

--
Performance 表演列表
--
获取所有表演列表
GET /performances
// page默认第一页；district默认全国
{ 
  page: "页数",
  district: "城市名字"
}
< 200
[
  {
    "id": 表演列表id,
    "progress": "状态",
    "areas": [
        "河南",
        "郑州"
    ],
    "address": "地址",
    "genre": "曲风",
    "kind": "演出类型",
    "bands_list": "乐队",
    "title": "表演列表标题",
    "description": "描述",
    "begin_at": "开始时间",
    "end_at": "结束时间",
    "city": "城市",
    "location": "场地",
    "coordinate": {
        #坐标
        "lat": "34.7644",
        "lng": "113.66924"
    },
    "poster": "演出海报(大)",
    "poster_thumb": "演出海报(小)",
    "albums_count": 相册数量,
    "favorites_count": 0,
    "favorite_id": null,
    "ticket": "门票价格",
    "tickets_count": 门票数量
  },
  {  },
  ...
]

--
City 热门城市
--
GET /cities
< 200
{ 
  cities: [
    #热门城市
    "北京",
    "上海"
  ]
}

--
Feature 专题
--
获取所有专题，只取权值最高3个专题
GET /features
< 200
[
  { 
    id: "专题id",
    title: "专题标题",
    description: "专题描述",
    banner_small: "专题小图片",
    banner: "专题大横幅",
  },
  { },
  ...
]

单个专题展示,(id放于URL后)
GET /features/:id
< 200
{ 
  id: "专题id",
  title: "专题标题",
  description: "专题描述",
  banner_small: "专题小图片",
  banner: "专题大横幅",
  performances: [
    { 
      //具体参考 /performances 里面参数返回
    },
    {  },
    ...
  ]
}

--
User 用户
--
weibo登录, 记得带

POST /fans/sns_login
{ 
  uid: uid,
  nickname: nickname,
  avatar: avatar,
  token: token,
  provider: provider
}
< 200
{ 
  success: true,
  id: 用户id,
  nickname: 用户姓名,
  auth_token: 登录token,
  email: 用户email,
  avatar: 用户头像
}
//登录失败
{{ "success": false, "message": "uid or provider must be provide" }, "status": 400 }

获取用户信息
GET /api/fans/profile
{ 
  auth_token: 用户token
}
< 200
{ 
  nickname: nickname,
  area: [用户地址],
  biography: 个人介绍，
  cellphone: 电话,
  gender: "男" or "女",
  avatar: avatar
}

--
Follow 关注

关注所有api都需要用户登录(auth_token)
--
关注列表

GET /api/follows
每页返回10条数据
{ 
  page: 页码,
}
< 200
[
  { //具体参考 /performances 里面参数返回  },
  ...
]

想去

POST /api/follows/want
{ 
  performance_id: 演出id
}
< 200
{ success: true }
//失败 
{ success: false, message: "验证不通过", errors: { "具体信息" } }

删除想去
DELETE /api/follows/want
{ 
  performance_id: 演出id
}
< 200
{ success: true }
//失败 
{ success: false }

感兴趣

POST /api/follows/interest
{ 
  performance_id: 演出id
}
< 200
{ success: true }
//失败 
{ success: false, message: "验证不通过", errors: { "具体信息" } }

删除感兴趣
DELETE /api/follows/interest
{ 
  performance_id: 演出id
}
< 200
{ success: true }
//失败 
{ success: false }


