FORMAT: 1A
HOST: http://youyanchu.gaiamagic.com/api

--- API for youyanchu.gaiamagic.com/api ---

--
Performance 表演列表
--
GET /performances
< 200
{
    "id": 表演列表id,
    "progress": "状态",
    "areas": [
        "河南",
        "郑州"
    ],
    "address": "地址",
    "genre": "曲风",
    "kind": "演出类型",
    "bands_list": "乐队",
    "title": "表演列表标题",
    "description": "描述",
    "begin_at": "开始时间",
    "end_at": "结束时间",
    "city": "城市",
    "location": "场地",
    "coordinate": {
        #坐标
        "lat": "34.7644",
        "lng": "113.66924"
    },
    "poster": "演出海报(大)",
    "poster_thumb": "演出海报(小)",
    "albums_count": 相册数量,
    "favorites_count": 0,
    "favorite_id": null,
    "ticket": "门票价格",
    "tickets_count": 门票数量
}
